### ISSUE TITLE
Missing `/`

### ISSUE THREAD

**Issue by jim-rosales** [oforir/Colmar_Academy#1]
For the video element, it looks like you're missing a `/` at the end. 

```
 <video class="main-container" src="resources/videos/thesis.mp4" controls poster="" id="vid-mob"/> 
```

https://github.com/oforir/Colmar_Academy/blob/f3d228296f9ce8cab7d77ea8e134717ed38fc541/index.html#L207

**Comment by oforir** [comment]
Thanks, will make sure to fix that. BTW - any clue how this might impact the structural integrity of the code?

**Comment by jim-rosales** [comment]
It won't have too much of an impact. The reason is that browsers are very lenient when it comes to syntax errors. They'll kinda just ignore it or add in what they think the correct syntax is.

Considering that though it's always best to avoid syntax errors because one day it could cause unexpected bugs.

**Comment by oforir** [comment]
ok, thanks
