### ISSUE TITLE
Missing ;

### ISSUE THREAD

**Issue by jim-rosales** [oforir/Colmar_Academy#2]
Nice job adding the copyright symbol via its entity reference! You do have a small syntax error though since the correct syntax to add a character via its entity reference is the following:
```
&copy;
```

https://github.com/oforir/Colmar_Academy/blob/f3d228296f9ce8cab7d77ea8e134717ed38fc541/index.html#L212

**Comment by oforir** [comment]
Good catch, thanks Jim.
